// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "AIzaSyAhO7cU7L7CNRPtoD3zvnMLHh8cdosHaL8",
  authDomain: "hope-care-3ae5b.firebaseapp.com",
  projectId: "hope-care-3ae5b",
  storageBucket: "hope-care-3ae5b.firebasestorage.app",
  messagingSenderId: "125402624757",
  appId: "1:125402624757:web:b0a3e642c344efb80e8bbc",
  measurementId: "G-267TE39SER"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const analytics = getAnalytics(app);