import { Router } from 'express';
import { authenticate, requireRoles } from '../middleware/auth';
import { validate } from '../middleware/validate';
import { historySchema, departmentSchema, hospitalSchema, bookingSchema, routeSchema, statusSchema, associationSchema } from '../validation/clinical';
import * as c from '../controllers/clinical';
const r = Router();
const auth = authenticate;
r.get('/departments', auth, requireRoles('PATIENT','DOCTOR','HOSPITAL','STAFF','ADMIN','NATIONAL_ADMIN'), c.departments);
r.post('/departments', auth, requireRoles('ADMIN','NATIONAL_ADMIN','STAFF'), validate(departmentSchema), c.createDepartment);
r.get('/hospitals', auth, requireRoles('PATIENT','DOCTOR','HOSPITAL','STAFF','ADMIN','NATIONAL_ADMIN'), c.hospitals);
r.post('/hospitals', auth, requireRoles('HOSPITAL','ADMIN','NATIONAL_ADMIN'), validate(hospitalSchema), c.createHospital);
r.post('/hospitals/doctors', auth, requireRoles('HOSPITAL','ADMIN','NATIONAL_ADMIN'), validate(associationSchema), c.associateDoctor);
r.get('/patients/me/medical-history', auth, requireRoles('PATIENT'), c.getHistory);
r.post('/patients/me/medical-history', auth, requireRoles('PATIENT'), validate(historySchema), c.addHistory);
r.post('/appointments', auth, requireRoles('PATIENT'), validate(bookingSchema), c.book);
r.get('/appointments', auth, requireRoles('PATIENT','DOCTOR','HOSPITAL','STAFF','ADMIN','NATIONAL_ADMIN'), c.listAppointments);
r.post('/appointments/:id/route', auth, requireRoles('HOSPITAL','ADMIN','NATIONAL_ADMIN'), validate(routeSchema), c.routeAppointment);
r.patch('/appointments/:id/status', auth, requireRoles('PATIENT','DOCTOR','HOSPITAL','ADMIN','NATIONAL_ADMIN'), validate(statusSchema), c.transitionAppointment);
export default r;
