import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import compression from 'compression';
import morgan from 'morgan';
import swaggerUi from 'swagger-ui-express';
import { openapi } from './openapi';
import auth from './routes/auth';
import placeholder from './routes/placeholder';
import clinical from './routes/clinical';
import patientCentric from './routes/patient-centric';
import { errorHandler } from './middleware/error';
import documents from './routes/documents';
import addresses from './routes/addresses';
const app = express();
app.use(helmet());
app.use(cors());
app.use(compression());
app.use(express.json({ limit: '1mb' }));
app.use(morgan('combined'));
app.get('/health', (_req, res) => res.json({ status: 'ok', service: 'hope-care' }));
app.use('/docs', swaggerUi.serve, swaggerUi.setup(openapi)); 
app.get('/openapi.json', (_req, res) => res.json(openapi)); 
app.use('/api/v1/auth', auth); 
app.use('/api/v1', clinical); 
app.use('/api/v1', patientCentric); 
app.use('/api/v1', documents);
app.use('/api/v1', addresses);
app.use('/api/v1', placeholder); 
app.use(errorHandler); 
export default app;
