export const openapi={openapi:'3.0.3',info:{title:'Hope-Care API',version:'1.0.0'},paths:{
'/health':{get:{responses:{'200':{description:'OK'}}}},
'/api/v1/auth/register':{post:{responses:{'201':{description:'Created'}}}},
'/api/v1/auth/login':{post:{responses:{'200':{description:'Authenticated'}}}},
'/api/v1/departments':{get:{responses:{'200':{description:'Departments'}}},post:{responses:{'201':{description:'Created'}}}},
'/api/v1/hospitals':{get:{summary:'List hospitals with address details and departments',responses:{'200':{description:'Hospitals with aggregated departments'}}},post:{summary:'Create a hospital with structured address/contact details',responses:{'201':{description:'Hospital created'}}}},
'/api/v1/patients/me/medical-history':{get:{responses:{'200':{description:'Medical history'}}},post:{responses:{'201':{description:'Created'}}}},
'/api/v1/appointments':{get:{responses:{'200':{description:'Appointments'}}},post:{responses:{'201':{description:'Created'}}}},
'/api/v1/appointments/{id}/route':{post:{responses:{'200':{description:'Routed'}}}},
'/api/v1/appointments/{id}/status':{patch:{responses:{'200':{description:'Status changed'}}}},
'/api/v1/documents/upload':{post:{summary:'Upload a private document (multipart field: file, documentType)',responses:{'201':{description:'Temporary document created'}}}},
'/api/v1/documents/{documentId}':{get:{responses:{'200':{description:'Document metadata'}}},delete:{responses:{'204':{description:'Deleted'}}}},
'/api/v1/documents/{documentId}/url':{get:{responses:{'200':{description:'Short-lived signed URL'}}}},
'/api/v1/patients/me/addresses':{get:{responses:{'200':{description:'Active current and permanent addresses'}}},post:{responses:{'201':{description:'Versioned address created'}}}},
'/api/v1/patients/me/addresses/history':{get:{responses:{'200':{description:'Address versions'}}}},
'/api/v1/patients/me/addresses/{addressId}':{get:{responses:{'200':{description:'Address'}}},put:{responses:{'201':{description:'New address version'}}}},
'/api/v1/patients/me/addresses/{addressId}/status-history':{get:{responses:{'200':{description:'Status history'}}}},
'/api/v1/patients/me/profile':{put:{responses:{'200':{description:'Profile photo attached'}}}},
}};
